services:
  database:
    image: 'postgres:latest'
    ports:
    - '5432:5432'
    environment:
    - 'POSTGRES_USER=omr'
    - 'POSTGRES_DB=omrkira'
    - 'POSTGRES_PASSWORD=kira309'
    volumes:
    - './columes/ecommerce/postgres:/var/lib/postgresql/data'